default:
  image: node:20
  tags:
    - gitlab-org-docker
  before_script:
    - node -v
    - npm -v

stages:
  - prepare
  - lint
  - test
  - release
  - doc
  - deploy

include:
  - /.gitlab-ci/stages.prepare.yml
  - /.gitlab-ci/stages.lint.yml
  - /.gitlab-ci/stages.test.yml
  - /.gitlab-ci/stages.release.yml
  - /.gitlab-ci/stages.doc.yml
  - /.gitlab-ci/stages.deploy.yml
